// Seed data for 40 canonical CoS autonomy actions
// Sourced from: sid-autonomy-actions-catalog skill, completion-tracker skill,
// GitHub FLEET tracker #3604 (R195 status), and recent merged PRs as of 2026-04-29.

export type AutonomyAction = {
  action_name: string;
  class: "sampling" | "paid_deal";
  action_number: number;
  display_name: string;
  description: string;
  handler_file: string;
  hitl_gate: "auto" | "tina_review" | "alex_decision";
  autonomy_level: "L0" | "L1" | "L2" | "L3";
  // % wired vs stub
  handler_pct: number;
  // % of action with real backtest fixtures (vs structural tests only)
  fixtures_pct: number;
  fixture_count: number;
  // % training data backfilled vs target
  training_backfill_pct: number;
  training_rows: number;
  training_target: number;
  // Latest eval pass rate
  eval_pass_pct: number | null;
  eval_corpus_size: number;
  // Status of evals
  eval_status: "none" | "structural_only" | "outcome_partial" | "outcome_full";
  // Production readiness score (0-100)
  prod_readiness_pct: number;
  // Gaps to full autonomy
  gaps_to_prod: string[];
  // Gaps to fully trained
  gaps_to_training: string[];
  // Where to find more training data (deep-dive list)
  data_sources: { source: string; description: string; estimated_rows: number; cleaning_steps: string[] }[];
  // Wiring plan to feed into training
  wiring_plan: string[];
  // Suggested new evals
  suggested_evals: string[];
  // Linked GitHub issues
  github_issues: number[];
};

const TINA = "tina_review" as const;
const AUTO = "auto" as const;
const ALEX = "alex_decision" as const;

// Common data source templates to keep this readable
const sourceReacher = (rows: number) => ({
  source: "Reacher API conversation logs",
  description: "Inbound + outbound creator messages, threaded by conversation_id; covers organic outreach + sampling responses",
  estimated_rows: rows,
  cleaning_steps: [
    "Drop test/internal accounts (whitelist by from_email)",
    "Strip personal contact info (PII redaction)",
    "Map intent → 20-category taxonomy via classifier v5",
    "Pair with downstream outcome (sample_sent / replied / converted)",
  ],
});

const sourceSlackMiqOps = (rows: number) => ({
  source: "Slack #miq-ops + brand channels",
  description: "Operator-discussion threads about routing decisions, escalations, and reactivation tactics",
  estimated_rows: rows,
  cleaning_steps: [
    "Filter to messages with reaction-emoji marking ground truth",
    "Resolve thread head → final outcome",
    "Strip employee PII",
    "Bucket by brand (37 channels) + by action_name via keyword map",
  ],
});

const sourceMonday = (rows: number) => ({
  source: "Monday.com Proposals + Portfolio boards",
  description: "Deal economics, retainer, affiliate GMV %, BL rate — gives reward signal for offer/contract actions",
  estimated_rows: rows,
  cleaning_steps: [
    "Join via shop_id ↔ brand_id",
    "Snapshot at deal_close_date to avoid leakage",
    "Drop deals < $1k retainer (noise)",
  ],
});

const sourceKalodata = (rows: number) => ({
  source: "Kalodata + Fastmoss creator/shop intelligence",
  description: "Creator GMV history, category fit, audience demos — for discovery/scoring/eligibility actions",
  estimated_rows: rows,
  cleaning_steps: [
    "Refresh staleness <30d",
    "Cross-ref with TikTok Shop API to remove banned accounts",
    "Normalize GMV to USD",
  ],
});

const sourceTikTokEvents = (rows: number) => ({
  source: "TikTok Shop order/fulfillment/post events",
  description: "Ground-truth outcomes: post counts, GMV, returns, refunds — closes the reward loop for payment + bundle actions",
  estimated_rows: rows,
  cleaning_steps: [
    "Dedupe by order_id",
    "Window: D+14 attribution",
    "Exclude refunded > 50% (fraud signal)",
  ],
});

const sourceFireflies = (rows: number) => ({
  source: "Fireflies sales + ops call transcripts",
  description: "Founder/AM negotiation language, objection handling, escalation moments — gold for offer/escalation actions",
  estimated_rows: rows,
  cleaning_steps: [
    "Speaker-attribute (Alex / AM / brand / creator)",
    "Segment by topic via Claude Opus pass",
    "Tag escalation moments with reason code",
  ],
});

const sourceGmail = (rows: number) => ({
  source: "Gmail BD threads (alex@, sales@)",
  description: "Outreach templates that converted, contract negotiations, payment escalations",
  estimated_rows: rows,
  cleaning_steps: [
    "Filter by labels (BD, Brand-Won, Brand-Churned)",
    "Threadify and tag with deal_stage at send time",
    "Redact financial routing numbers",
  ],
});

const sourceCosRuns = (rows: number) => ({
  source: "momentiq_cos.cos_runs + cos_run_errors",
  description: "Self-source: every dispatched run with input payload, output, HITL decision, error class — primary backtest fuel",
  estimated_rows: rows,
  cleaning_steps: [
    "Filter status IN ('SUCCESS','HITL_RESOLVED')",
    "Join hitl_decisions to recover human label",
    "Bucket by handler_version to avoid mixing eras",
  ],
});

export const ACTIONS: AutonomyAction[] = [
  // ============ SAMPLING (14) ============
  {
    action_name: "generate_creative_brief",
    class: "sampling",
    action_number: 1,
    display_name: "Generate Creative Brief",
    description: "Compose per-brand creative brief from product + brand kit + recent winning content.",
    handler_file: "campaign-actions-core.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 90,
    fixtures_pct: 30,
    fixture_count: 18,
    training_backfill_pct: 25,
    training_rows: 124,
    training_target: 500,
    eval_pass_pct: 78,
    eval_corpus_size: 18,
    eval_status: "structural_only",
    prod_readiness_pct: 55,
    gaps_to_prod: [
      "No brand-voice fidelity scorer (manual review only)",
      "Brief→post outcome reward not joined",
      "Tina_review gate still fires on 100% of briefs",
    ],
    gaps_to_training: [
      "Need 376 more brief↔winning-post pairs",
      "Need brand-voice gold examples per shop (37 shops × ~10)",
      "Need anti-pattern set (rejected briefs with reason)",
    ],
    data_sources: [
      sourceCosRuns(120),
      sourceSlackMiqOps(60),
      sourceFireflies(40),
      {
        source: "Brand kit Drive folder",
        description: "Voice guidelines, reference posts, banned phrases per shop",
        estimated_rows: 370,
        cleaning_steps: ["Parse PDF/DOCX via doc-extract", "Tag by shop_id"],
      },
    ],
    wiring_plan: [
      "Add CARE-style brand voice scorer (5-dim: tone, format, claims, hooks, CTA)",
      "Backfill 376 briefs from existing campaign archive",
      "Pair each brief to first-3-posts CTR/GMV (D+14 attribution)",
      "Promote to L1 shadow once eval ≥ 90% on 200-case corpus",
    ],
    suggested_evals: [
      "Brand-voice fidelity ≥ 0.85 cosine vs gold corpus",
      "Banned-phrase regex pass rate = 100%",
      "Outcome reward: posts using brief outperform baseline by ≥ 5% CTR",
    ],
    github_issues: [],
  },
  {
    action_name: "validate_brand_assets",
    class: "sampling",
    action_number: 2,
    display_name: "Validate Brand Assets",
    description: "Confirm brand has logo, color palette, banned-phrase list, and 3+ reference posts.",
    handler_file: "campaign-actions-core.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 100,
    fixtures_pct: 80,
    fixture_count: 47,
    training_backfill_pct: 80,
    training_rows: 296,
    training_target: 370,
    eval_pass_pct: 96,
    eval_corpus_size: 47,
    eval_status: "structural_only",
    prod_readiness_pct: 88,
    gaps_to_prod: [
      "No automated re-validation cron (assets drift over time)",
    ],
    gaps_to_training: ["Need 74 more shop fixtures with intentionally-broken assets"],
    data_sources: [sourceCosRuns(74), {
      source: "Brand-asset Drive audit script",
      description: "Walks all 37 brand folders and reports missing assets",
      estimated_rows: 200,
      cleaning_steps: ["Run weekly audit", "Diff against last snapshot"],
    }],
    wiring_plan: [
      "Daily cron re-validates all active brands",
      "Emit autonomy_contract event on missing-asset detection",
    ],
    suggested_evals: ["Recall on intentional-omission test set ≥ 0.95"],
    github_issues: [],
  },
  {
    action_name: "publish_compliance_rules",
    class: "sampling",
    action_number: 3,
    display_name: "Publish Compliance Rules",
    description: "Push per-brand FTC + claim-restriction rules to messaging agent.",
    handler_file: "campaign-actions-core.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 85,
    fixtures_pct: 40,
    fixture_count: 22,
    training_backfill_pct: 30,
    training_rows: 110,
    training_target: 370,
    eval_pass_pct: 82,
    eval_corpus_size: 22,
    eval_status: "structural_only",
    prod_readiness_pct: 60,
    gaps_to_prod: [
      "No legal-review handoff",
      "Banned-claim regex hand-maintained, not learned",
    ],
    gaps_to_training: ["260 more brand-rule sets needed"],
    data_sources: [
      {
        source: "Legal Drive (compliance bibles)",
        description: "FTC + per-category claim rules (supplements vs beauty)",
        estimated_rows: 260,
        cleaning_steps: ["Parse PDF rules", "Map to canonical category taxonomy"],
      },
      sourceSlackMiqOps(50),
    ],
    wiring_plan: [
      "Auto-generate per-brand rule pack from category template + brand overrides",
      "Add legal_review HITL gate before publish",
    ],
    suggested_evals: ["Banned-claim test corpus pass = 100%", "FTC disclosure presence on 100% of generated content"],
    github_issues: [],
  },
  {
    action_name: "discover_creators",
    class: "sampling",
    action_number: 4,
    display_name: "Discover Creators",
    description: "Source candidate creator pool from TikTok Shop, Kalodata, Fastmoss for a brand.",
    handler_file: "creator-actions-discovery.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 95,
    fixtures_pct: 100,
    fixture_count: 100,
    training_backfill_pct: 75,
    training_rows: 750,
    training_target: 1000,
    eval_pass_pct: 92,
    eval_corpus_size: 100,
    eval_status: "outcome_partial",
    prod_readiness_pct: 80,
    gaps_to_prod: ["Outcome ladder added but conversion-rate reward not yet joined", "No category-cold-start strategy"],
    gaps_to_training: ["Need 250 more discovery runs with full outcome chain"],
    data_sources: [sourceKalodata(800), sourceCosRuns(750), sourceTikTokEvents(500)],
    wiring_plan: [
      "Already shipped outcome ladder + 100 fixtures + learning-engine scoring (#3614)",
      "Backfill conversion-rate reward at D+14",
      "Seed cold-start policy from category embeddings",
    ],
    suggested_evals: ["Top-50 precision ≥ 0.6 (creator replied)", "GMV-weighted recall ≥ 0.7"],
    github_issues: [3614],
  },
  {
    action_name: "score_and_select_creators",
    class: "sampling",
    action_number: 5,
    display_name: "Score & Select Creators",
    description: "Rank creator pool against brand fit + historical conversion.",
    handler_file: "creator-actions-scoring.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 80,
    fixtures_pct: 60,
    fixture_count: 35,
    training_backfill_pct: 40,
    training_rows: 200,
    training_target: 500,
    eval_pass_pct: 84,
    eval_corpus_size: 35,
    eval_status: "structural_only",
    prod_readiness_pct: 65,
    gaps_to_prod: ["Tina_review gate fires 100% — no auto-approve threshold tuned"],
    gaps_to_training: ["300 more scored-then-outcomed creators needed"],
    data_sources: [sourceKalodata(500), sourceCosRuns(200), sourceTikTokEvents(300)],
    wiring_plan: [
      "Train ranker on (creator_features, outcome) pairs",
      "Set auto-approve at p_convert > 0.4 (tune via shadow)",
    ],
    suggested_evals: ["Auto-approve precision ≥ 0.85", "NDCG@20 ≥ 0.7 vs human-curated rankings"],
    github_issues: [],
  },
  {
    action_name: "evaluate_creator_eligibility",
    class: "sampling",
    action_number: 6,
    display_name: "Evaluate Creator Eligibility",
    description: "Hard-rule eligibility (active, region, category, prior-banned check).",
    handler_file: "creator-actions-scoring.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 100,
    fixtures_pct: 90,
    fixture_count: 60,
    training_backfill_pct: 90,
    training_rows: 540,
    training_target: 600,
    eval_pass_pct: 98,
    eval_corpus_size: 60,
    eval_status: "outcome_partial",
    prod_readiness_pct: 92,
    gaps_to_prod: ["Banned-creator list refresh cron missing"],
    gaps_to_training: [],
    data_sources: [sourceCosRuns(540), {
      source: "TikTok Shop banned-account API",
      description: "Daily list of banned/suspended accounts",
      estimated_rows: 60,
      cleaning_steps: ["Daily refresh", "Cache in Neon"],
    }],
    wiring_plan: ["Add daily banned-list refresh cron"],
    suggested_evals: ["Banned-creator detection recall = 1.0"],
    github_issues: [],
  },
  {
    action_name: "draft_outreach_messages",
    class: "sampling",
    action_number: 7,
    display_name: "Draft Outreach Messages",
    description: "Generate personalized first-touch message per creator using messaging agent (CARE).",
    handler_file: "creator-actions-shared.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 95,
    fixtures_pct: 70,
    fixture_count: 240,
    training_backfill_pct: 50,
    training_rows: 640,
    training_target: 1280,
    eval_pass_pct: 88,
    eval_corpus_size: 240,
    eval_status: "outcome_partial",
    prod_readiness_pct: 75,
    gaps_to_prod: [
      "Tina_review still 100%",
      "Per-shop voice fine-tune not loaded for 14/37 shops",
    ],
    gaps_to_training: ["49 cross-shop learnings seeded; need 1,231 more gold pairs"],
    data_sources: [
      sourceReacher(2000),
      sourceCosRuns(640),
      {
        source: "ops_platform_messaging_agent_cross_shop_learnings",
        description: "49 seeded cross-shop learnings — gold/anti/intent patterns",
        estimated_rows: 49,
        cleaning_steps: ["Already curated"],
      },
    ],
    wiring_plan: [
      "Backfill 1,231 gold first-touch → reply pairs from Reacher",
      "Fine-tune per-shop voice for remaining 14 brands",
      "Promote to auto-send at CARE ≥ 0.85 once eval clears",
    ],
    suggested_evals: ["CARE composite ≥ 0.85", "Reply rate uplift ≥ 10% vs control template"],
    github_issues: [],
  },
  {
    action_name: "validate_draft_quality",
    class: "sampling",
    action_number: 8,
    display_name: "Validate Draft Quality",
    description: "CARE scorer + banned-phrase + length checks before send.",
    handler_file: "creator-actions-shared.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 100,
    fixtures_pct: 95,
    fixture_count: 120,
    training_backfill_pct: 85,
    training_rows: 425,
    training_target: 500,
    eval_pass_pct: 94,
    eval_corpus_size: 120,
    eval_status: "outcome_partial",
    prod_readiness_pct: 90,
    gaps_to_prod: ["No drift monitor on CARE distribution"],
    gaps_to_training: ["75 more anti-pattern fixtures"],
    data_sources: [sourceCosRuns(425), sourceReacher(200)],
    wiring_plan: ["Add page-hinkley drift monitor on CARE score (#3363)"],
    suggested_evals: ["CARE auto-pass precision ≥ 0.95", "Banned-phrase recall = 1.0"],
    github_issues: [3363],
  },
  {
    action_name: "send_creator_message",
    class: "sampling",
    action_number: 9,
    display_name: "Send Creator Message",
    description: "Dispatch via TikTok Shop messaging API + record send_id.",
    handler_file: "creator-actions-shared.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 100,
    fixtures_pct: 100,
    fixture_count: 80,
    training_backfill_pct: 60,
    training_rows: 600,
    training_target: 1000,
    eval_pass_pct: 99,
    eval_corpus_size: 80,
    eval_status: "outcome_partial",
    prod_readiness_pct: 80,
    gaps_to_prod: [
      "Tina_review gate is gating dispatch — should be auto post-validation",
      "No de-duplication guard (resend within 7d possible)",
    ],
    gaps_to_training: ["400 more send→reply pairs"],
    data_sources: [sourceReacher(1500), sourceCosRuns(600), sourceTikTokEvents(800)],
    wiring_plan: [
      "Flip gate to AUTO once validate_draft_quality reaches L2",
      "Add 7-day de-dup guard (P2-SKILL gap)",
    ],
    suggested_evals: ["API success ≥ 99.5%", "De-dup violation = 0"],
    github_issues: [],
  },
  {
    action_name: "detect_and_route_intent",
    class: "sampling",
    action_number: 10,
    display_name: "Detect & Route Intent",
    description: "Classify creator reply intent across 20-category taxonomy + route.",
    handler_file: "notification-actions.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 100,
    fixtures_pct: 100,
    fixture_count: 1088,
    training_backfill_pct: 95,
    training_rows: 1088,
    training_target: 1200,
    eval_pass_pct: 99,
    eval_corpus_size: 1088,
    eval_status: "outcome_full",
    prod_readiness_pct: 95,
    gaps_to_prod: [
      "11 residual dual-intent failures",
      "Per-shop budget throttle live but not tuned per brand",
    ],
    gaps_to_training: ["112 more dual-intent edge cases"],
    data_sources: [sourceReacher(2000), sourceCosRuns(1088)],
    wiring_plan: [
      "Already wired hybrid v5 classifier (#3613, #3605, #3606, #3607)",
      "Tune $50/day budget throttle per brand based on volume",
      "Resolve 11 residual dual-intent cases via Anthropic Opus tie-break",
    ],
    suggested_evals: ["Top-1 accuracy ≥ 99.5% on 1.2k corpus", "Latency p95 < 500ms"],
    github_issues: [3605, 3606, 3607, 3613],
  },
  {
    action_name: "evaluate_offer_request",
    class: "sampling",
    action_number: 11,
    display_name: "Evaluate Offer Request",
    description: "When creator requests sample, decide approve/counter/decline.",
    handler_file: "sampling-queue-handlers.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 90,
    fixtures_pct: 100,
    fixture_count: 100,
    training_backfill_pct: 70,
    training_rows: 350,
    training_target: 500,
    eval_pass_pct: 91,
    eval_corpus_size: 100,
    eval_status: "outcome_partial",
    prod_readiness_pct: 78,
    gaps_to_prod: ["3-way decision now live (#3616), still tina-gated"],
    gaps_to_training: ["150 more counter-offer outcomes"],
    data_sources: [sourceReacher(500), sourceCosRuns(350), sourceMonday(80)],
    wiring_plan: [
      "Promote to auto for high-confidence approves once 200-case eval ≥ 95%",
      "Tune counter-offer threshold via shadow",
    ],
    suggested_evals: ["3-way decision agreement with Tina ≥ 0.9", "Counter→accept rate uplift ≥ 5%"],
    github_issues: [3616],
  },
  {
    action_name: "auto_approve_or_route_to_hitl",
    class: "sampling",
    action_number: 12,
    display_name: "Auto-Approve or Route to HITL",
    description: "Threshold gate: high-confidence offers auto-approve, rest route to Tina.",
    handler_file: "sampling-queue-handlers.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 100,
    fixtures_pct: 100,
    fixture_count: 28,
    training_backfill_pct: 100,
    training_rows: 28,
    training_target: 28,
    eval_pass_pct: 100,
    eval_corpus_size: 28,
    eval_status: "outcome_partial",
    prod_readiness_pct: 95,
    gaps_to_prod: ["Need scaled corpus beyond 28 cases for confidence"],
    gaps_to_training: ["Expand corpus to 200 cases"],
    data_sources: [sourceCosRuns(200), sourceReacher(150)],
    wiring_plan: ["Already shipped (#3608) at 100% — expand corpus to 200"],
    suggested_evals: ["Auto-approve precision ≥ 0.95 at scale"],
    github_issues: [3608],
  },
  {
    action_name: "send_approval_response",
    class: "sampling",
    action_number: 13,
    display_name: "Send Approval Response",
    description: "Send approval/decline message via messaging agent.",
    handler_file: "sampling-queue-handlers.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 95,
    fixtures_pct: 60,
    fixture_count: 30,
    training_backfill_pct: 40,
    training_rows: 200,
    training_target: 500,
    eval_pass_pct: 86,
    eval_corpus_size: 30,
    eval_status: "structural_only",
    prod_readiness_pct: 65,
    gaps_to_prod: ["Tina_review gate", "No A/B template testing"],
    gaps_to_training: ["300 more approval-response→sample-sent pairs"],
    data_sources: [sourceReacher(800), sourceCosRuns(200)],
    wiring_plan: [
      "Add template A/B harness with multi-armed bandit",
      "Backfill 300 historic approval responses with outcome",
    ],
    suggested_evals: ["Sample-sent rate ≥ 90%", "Reply-back rate ≥ 30%"],
    github_issues: [],
  },
  {
    action_name: "record_outcome",
    class: "sampling",
    action_number: 14,
    display_name: "Record Outcome",
    description: "Capture sample-shipped, post-published, GMV outcomes; emit learning hook.",
    handler_file: "notification-actions.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 75,
    fixtures_pct: 50,
    fixture_count: 40,
    training_backfill_pct: 30,
    training_rows: 300,
    training_target: 1000,
    eval_pass_pct: 80,
    eval_corpus_size: 40,
    eval_status: "structural_only",
    prod_readiness_pct: 60,
    gaps_to_prod: [
      "TikTok event ingestion partial — only orders, not posts",
      "D+14 attribution job not scheduled",
    ],
    gaps_to_training: ["700 more outcome records needed"],
    data_sources: [sourceTikTokEvents(2000), sourceCosRuns(300)],
    wiring_plan: [
      "Wire DATA-TTS-EVENTS ingest (per FLEET tracker Phase D)",
      "Schedule D+14 attribution cron",
    ],
    suggested_evals: ["Outcome capture rate ≥ 95% within D+14"],
    github_issues: [],
  },

  // ============ PAID DEAL (26) ============
  {
    action_name: "calculate_reactivation_roi_potential",
    class: "paid_deal",
    action_number: 1,
    display_name: "Calculate Reactivation ROI Potential",
    description: "For dormant creators, project ROI of win-back outreach.",
    handler_file: "creator-actions-retention.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 70,
    fixtures_pct: 30,
    fixture_count: 18,
    training_backfill_pct: 25,
    training_rows: 125,
    training_target: 500,
    eval_pass_pct: 75,
    eval_corpus_size: 18,
    eval_status: "structural_only",
    prod_readiness_pct: 50,
    gaps_to_prod: ["6 retention handlers still partly stubbed", "Multi-brand support pending"],
    gaps_to_training: ["375 more dormant→reactivated pairs across 5+ brands"],
    data_sources: [sourceCosRuns(125), sourceTikTokEvents(500), sourceMonday(40)],
    wiring_plan: [
      "Finish de-stubbing 6 retention handlers (P3-REACTIVATION skill)",
      "Backfill from PSH + 4 other brands' dormant lists",
    ],
    suggested_evals: ["ROI projection MAE ≤ 20% vs realized D+30"],
    github_issues: [],
  },
  {
    action_name: "evaluate_reactivation_eligibility",
    class: "paid_deal",
    action_number: 2,
    display_name: "Evaluate Reactivation Eligibility",
    description: "Filter dormant creators on cooldown, opt-out, GMV floor.",
    handler_file: "creator-actions-retention.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 90,
    fixtures_pct: 80,
    fixture_count: 50,
    training_backfill_pct: 70,
    training_rows: 350,
    training_target: 500,
    eval_pass_pct: 95,
    eval_corpus_size: 50,
    eval_status: "outcome_partial",
    prod_readiness_pct: 85,
    gaps_to_prod: ["Cooldown timer reads from Reacher only — should also check messaging-agent send log"],
    gaps_to_training: ["150 more eligibility rejections with reason"],
    data_sources: [sourceCosRuns(350), sourceReacher(500)],
    wiring_plan: ["Unify cooldown source-of-truth across messaging surfaces"],
    suggested_evals: ["Cooldown violation rate = 0", "Opt-out respect rate = 100%"],
    github_issues: [],
  },
  {
    action_name: "identify_top_sellers_needing_push",
    class: "paid_deal",
    action_number: 3,
    display_name: "Identify Top Sellers Needing Push",
    description: "Find active creators trending down → trigger LTV push campaign.",
    handler_file: "creator-actions-retention.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 80,
    fixtures_pct: 50,
    fixture_count: 25,
    training_backfill_pct: 35,
    training_rows: 175,
    training_target: 500,
    eval_pass_pct: 82,
    eval_corpus_size: 25,
    eval_status: "structural_only",
    prod_readiness_pct: 60,
    gaps_to_prod: ["Trend-detection algorithm hand-tuned thresholds"],
    gaps_to_training: ["325 more push→outcome pairs"],
    data_sources: [sourceTikTokEvents(1500), sourceCosRuns(175)],
    wiring_plan: ["Replace static thresholds with learned change-point model"],
    suggested_evals: ["Top-50 push precision ≥ 0.7 at D+30 GMV uplift"],
    github_issues: [],
  },
  {
    action_name: "calculate_ltv_push_roi_potential",
    class: "paid_deal",
    action_number: 4,
    display_name: "Calculate LTV Push ROI",
    description: "ROI projection for pushing existing top-sellers to new bundles.",
    handler_file: "creator-actions-retention.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 65,
    fixtures_pct: 25,
    fixture_count: 15,
    training_backfill_pct: 20,
    training_rows: 100,
    training_target: 500,
    eval_pass_pct: 70,
    eval_corpus_size: 15,
    eval_status: "structural_only",
    prod_readiness_pct: 45,
    gaps_to_prod: ["Stub-heavy handler", "No bundle pricing intel join"],
    gaps_to_training: ["400 more push outcomes"],
    data_sources: [sourceTikTokEvents(2000), sourceMonday(50)],
    wiring_plan: ["Join bundle-pricing intel from query_pricing_intelligence", "De-stub handler internals"],
    suggested_evals: ["ROI MAE ≤ 25%"],
    github_issues: [],
  },
  {
    action_name: "query_pricing_intelligence",
    class: "paid_deal",
    action_number: 5,
    display_name: "Query Pricing Intelligence",
    description: "Pull category pricing benchmarks from Kalodata + historical deals.",
    handler_file: "campaign-actions-pricing.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 100,
    fixtures_pct: 70,
    fixture_count: 80,
    training_backfill_pct: 60,
    training_rows: 600,
    training_target: 1000,
    eval_pass_pct: 90,
    eval_corpus_size: 80,
    eval_status: "outcome_partial",
    prod_readiness_pct: 82,
    gaps_to_prod: ["Kalodata staleness can hit 30d+ for niche categories"],
    gaps_to_training: ["400 more category-coverage rows"],
    data_sources: [sourceKalodata(2000), sourceMonday(283)],
    wiring_plan: ["Add Kalodata refresh-on-demand for thin categories"],
    suggested_evals: ["Pricing recommendation MAPE ≤ 15% vs accepted offer"],
    github_issues: [],
  },
  {
    action_name: "get_historical_gmv",
    class: "paid_deal",
    action_number: 6,
    display_name: "Get Historical GMV",
    description: "Lookup creator's prior GMV across deals + organic for offer baseline.",
    handler_file: "campaign-actions-pricing.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 100,
    fixtures_pct: 95,
    fixture_count: 100,
    training_backfill_pct: 95,
    training_rows: 950,
    training_target: 1000,
    eval_pass_pct: 99,
    eval_corpus_size: 100,
    eval_status: "outcome_full",
    prod_readiness_pct: 96,
    gaps_to_prod: [],
    gaps_to_training: [],
    data_sources: [sourceTikTokEvents(5000), sourceCosRuns(950)],
    wiring_plan: ["No work needed — keep monitoring drift"],
    suggested_evals: ["Lookup latency p95 < 200ms"],
    github_issues: [],
  },
  {
    action_name: "calculate_optimal_offer",
    class: "paid_deal",
    action_number: 7,
    display_name: "Calculate Optimal Offer",
    description: "Combine pricing intel + historical GMV → recommended offer (commission %, fixed rate, bundle).",
    handler_file: "campaign-actions-pricing.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 95,
    fixtures_pct: 100,
    fixture_count: 283,
    training_backfill_pct: 100,
    training_rows: 283,
    training_target: 283,
    eval_pass_pct: 100,
    eval_corpus_size: 283,
    eval_status: "outcome_full",
    prod_readiness_pct: 92,
    gaps_to_prod: ["Tina_review still 100% on offer send"],
    gaps_to_training: [],
    data_sources: [sourceMonday(283), sourceKalodata(800), sourceFireflies(150)],
    wiring_plan: ["Promote to auto-send when accept-rate ≥ 70% in shadow"],
    suggested_evals: ["Accept rate ≥ 0.7 vs human-set offers"],
    github_issues: [],
  },
  {
    action_name: "send_offer",
    class: "paid_deal",
    action_number: 8,
    display_name: "Send Offer",
    description: "Dispatch offer message + log offer state.",
    handler_file: "campaign-actions-core.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 100,
    fixtures_pct: 90,
    fixture_count: 100,
    training_backfill_pct: 80,
    training_rows: 800,
    training_target: 1000,
    eval_pass_pct: 97,
    eval_corpus_size: 100,
    eval_status: "outcome_full",
    prod_readiness_pct: 88,
    gaps_to_prod: ["Per-creator de-dup guard missing"],
    gaps_to_training: ["200 more offer→accept pairs across new categories"],
    data_sources: [sourceReacher(1500), sourceCosRuns(800)],
    wiring_plan: ["Add 14d de-dup guard before send"],
    suggested_evals: ["Send success ≥ 99%", "Reply rate ≥ 25%"],
    github_issues: [],
  },
  {
    action_name: "evaluate_counter_offer",
    class: "paid_deal",
    action_number: 9,
    display_name: "Evaluate Counter Offer",
    description: "When creator counters, decide accept/counter/decline.",
    handler_file: "campaign-actions-core.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 90,
    fixtures_pct: 60,
    fixture_count: 50,
    training_backfill_pct: 35,
    training_rows: 175,
    training_target: 500,
    eval_pass_pct: 85,
    eval_corpus_size: 50,
    eval_status: "structural_only",
    prod_readiness_pct: 65,
    gaps_to_prod: ["No founder-style negotiation pattern learned"],
    gaps_to_training: ["325 more counter→outcome rounds"],
    data_sources: [sourceReacher(800), sourceFireflies(200), sourceCosRuns(175)],
    wiring_plan: [
      "Mine Fireflies for Alex's negotiation moves; train counter-pattern",
      "Wire generate_counter_response (#3617) into the loop",
    ],
    suggested_evals: ["Counter→accept rate ≥ baseline", "Margin preservation ≥ 0.85"],
    github_issues: [3617],
  },
  {
    action_name: "check_roas_projection",
    class: "paid_deal",
    action_number: 10,
    display_name: "Check ROAS Projection",
    description: "Project ROAS at proposed offer + creator profile.",
    handler_file: "campaign-actions-pricing.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 95,
    fixtures_pct: 80,
    fixture_count: 75,
    training_backfill_pct: 70,
    training_rows: 350,
    training_target: 500,
    eval_pass_pct: 92,
    eval_corpus_size: 75,
    eval_status: "outcome_partial",
    prod_readiness_pct: 80,
    gaps_to_prod: ["Cold-start variance high for new creators"],
    gaps_to_training: ["150 more ROAS→realized pairs"],
    data_sources: [sourceTikTokEvents(2000), sourceMonday(283)],
    wiring_plan: ["Add prior-belief regularization for low-history creators"],
    suggested_evals: ["ROAS MAPE ≤ 25%"],
    github_issues: [],
  },
  {
    action_name: "auto_accept_or_route_to_hitl",
    class: "paid_deal",
    action_number: 11,
    display_name: "Auto-Accept or Route to HITL",
    description: "Threshold gate on counter-offer / inbound deal.",
    handler_file: "campaign-actions-core.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 100,
    fixtures_pct: 75,
    fixture_count: 40,
    training_backfill_pct: 60,
    training_rows: 240,
    training_target: 400,
    eval_pass_pct: 91,
    eval_corpus_size: 40,
    eval_status: "structural_only",
    prod_readiness_pct: 75,
    gaps_to_prod: ["Threshold not learned per shop"],
    gaps_to_training: ["160 more decisions"],
    data_sources: [sourceCosRuns(240), sourceReacher(500)],
    wiring_plan: ["Tune per-shop accept threshold via Bayesian optimizer"],
    suggested_evals: ["Auto-accept precision ≥ 0.95"],
    github_issues: [],
  },
  {
    action_name: "generate_agreement",
    class: "paid_deal",
    action_number: 12,
    display_name: "Generate Agreement",
    description: "Build contract DOCX from template + offer terms.",
    handler_file: "queue-organic-handlers.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 90,
    fixtures_pct: 50,
    fixture_count: 25,
    training_backfill_pct: 45,
    training_rows: 225,
    training_target: 500,
    eval_pass_pct: 88,
    eval_corpus_size: 25,
    eval_status: "structural_only",
    prod_readiness_pct: 65,
    gaps_to_prod: ["Template variants per state/category limited"],
    gaps_to_training: ["275 more contract→countersigned pairs"],
    data_sources: [
      {
        source: "Dropbox Sign envelope archive",
        description: "All historic agreements with sign status + edits",
        estimated_rows: 1500,
        cleaning_steps: ["Diff sent vs signed for negotiated edits", "Tag rejection reason"],
      },
      sourceMonday(283),
    ],
    wiring_plan: [
      "Train template-selector on state × category × deal_size",
      "Backfill from Dropbox Sign archive",
    ],
    suggested_evals: ["Countersign rate ≥ 0.8 with no edits"],
    github_issues: [],
  },
  {
    action_name: "send_contract",
    class: "paid_deal",
    action_number: 13,
    display_name: "Send Contract",
    description: "Dispatch via Dropbox Sign + track signature events.",
    handler_file: "queue-organic-handlers.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 100,
    fixtures_pct: 95,
    fixture_count: 80,
    training_backfill_pct: 90,
    training_rows: 720,
    training_target: 800,
    eval_pass_pct: 98,
    eval_corpus_size: 80,
    eval_status: "outcome_full",
    prod_readiness_pct: 92,
    gaps_to_prod: ["Tina_review still firing — should be auto post-generate"],
    gaps_to_training: [],
    data_sources: [{
      source: "Dropbox Sign API events",
      description: "Sent / viewed / signed events",
      estimated_rows: 2000,
      cleaning_steps: ["Join to Monday deal", "Tag time-to-sign"],
    }],
    wiring_plan: ["Flip to auto post-generate"],
    suggested_evals: ["Send success ≥ 99.5%", "Time-to-sign p50 < 48h"],
    github_issues: [],
  },
  {
    action_name: "request_w9",
    class: "paid_deal",
    action_number: 14,
    display_name: "Request W-9",
    description: "Send W-9 collection request when creator approaches $600 threshold.",
    handler_file: "notification-actions.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 60,
    fixtures_pct: 30,
    fixture_count: 12,
    training_backfill_pct: 20,
    training_rows: 100,
    training_target: 500,
    eval_pass_pct: 80,
    eval_corpus_size: 12,
    eval_status: "structural_only",
    prod_readiness_pct: 50,
    gaps_to_prod: [
      "No W-9 collection pipeline — only stage logic in PA evaluator",
      "No threshold alert before $600 hits",
    ],
    gaps_to_training: ["400 more request→collected pairs"],
    data_sources: [sourceTikTokEvents(800), sourceGmail(300)],
    wiring_plan: [
      "Build standalone W-9 collection pipeline (P2-SKILL gap)",
      "Add threshold alert at $500 cumulative",
    ],
    suggested_evals: ["W-9 collected before $600 = 100%"],
    github_issues: [],
  },
  {
    action_name: "set_content_brief_if_new",
    class: "paid_deal",
    action_number: 15,
    display_name: "Set Content Brief If New",
    description: "Push deal-specific brief to creator if not already set.",
    handler_file: "campaign-actions-core.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 90,
    fixtures_pct: 70,
    fixture_count: 35,
    training_backfill_pct: 60,
    training_rows: 240,
    training_target: 400,
    eval_pass_pct: 89,
    eval_corpus_size: 35,
    eval_status: "structural_only",
    prod_readiness_pct: 75,
    gaps_to_prod: ["No brief→post-quality reward join"],
    gaps_to_training: ["160 more brief→post quality pairs"],
    data_sources: [sourceCosRuns(240), sourceTikTokEvents(500)],
    wiring_plan: ["Join post-quality scorer (action 16) outcomes back to brief"],
    suggested_evals: ["Post-quality lift ≥ 5% with brief vs without"],
    github_issues: [],
  },
  {
    action_name: "auto_approve_or_request_revision",
    class: "paid_deal",
    action_number: 16,
    display_name: "Auto-Approve or Request Revision",
    description: "Score posted content; auto-approve high-quality, request revision otherwise.",
    handler_file: "sampling-queue-handlers-quality.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 95,
    fixtures_pct: 80,
    fixture_count: 60,
    training_backfill_pct: 70,
    training_rows: 350,
    training_target: 500,
    eval_pass_pct: 90,
    eval_corpus_size: 60,
    eval_status: "outcome_partial",
    prod_readiness_pct: 80,
    gaps_to_prod: ["Tina_review still 100% — quality scorer not trusted yet at L1"],
    gaps_to_training: ["150 more post→revised pairs"],
    data_sources: [sourceTikTokEvents(2000), sourceCosRuns(350)],
    wiring_plan: ["Promote scorer to L1 shadow once eval ≥ 90% on 200-case corpus"],
    suggested_evals: ["Auto-approve precision ≥ 0.9 vs Tina label"],
    github_issues: [],
  },
  {
    action_name: "count_qualifying_posts",
    class: "paid_deal",
    action_number: 17,
    display_name: "Count Qualifying Posts",
    description: "Money-path: count posts that meet contract criteria for payment.",
    handler_file: "campaign-actions-payment.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 100,
    fixtures_pct: 100,
    fixture_count: 50,
    training_backfill_pct: 95,
    training_rows: 475,
    training_target: 500,
    eval_pass_pct: 100,
    eval_corpus_size: 50,
    eval_status: "outcome_full",
    prod_readiness_pct: 95,
    gaps_to_prod: ["MONEY_PATH — kept tina-gated for safety; consider promoting"],
    gaps_to_training: [],
    data_sources: [sourceTikTokEvents(3000), sourceCosRuns(475)],
    wiring_plan: ["Already shipped (#3460) — gate flip pending V31_ALEX_KILL_SWITCH review"],
    suggested_evals: ["Count agreement with manual audit = 100%"],
    github_issues: [3460],
  },
  {
    action_name: "verify_bundle_completion",
    class: "paid_deal",
    action_number: 18,
    display_name: "Verify Bundle Completion",
    description: "Money-path: verify all contracted deliverables met before payment.",
    handler_file: "campaign-actions-payment.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 100,
    fixtures_pct: 90,
    fixture_count: 45,
    training_backfill_pct: 85,
    training_rows: 425,
    training_target: 500,
    eval_pass_pct: 99,
    eval_corpus_size: 45,
    eval_status: "outcome_full",
    prod_readiness_pct: 92,
    gaps_to_prod: ["MONEY_PATH — fixed param-trust drift in #3466; tina-gated"],
    gaps_to_training: ["75 more verification cases"],
    data_sources: [sourceTikTokEvents(2000), sourceCosRuns(425)],
    wiring_plan: ["Maintain tina-gate; no promotion until 200-case audit passes"],
    suggested_evals: ["Verification recall = 1.0 (no false-pass)"],
    github_issues: [3278, 3466],
  },
  {
    action_name: "calculate_total_compensation",
    class: "paid_deal",
    action_number: 19,
    display_name: "Calculate Total Compensation",
    description: "Money-path: compute total payout = base + bonuses + commission.",
    handler_file: "campaign-actions-payment.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 95,
    fixtures_pct: 85,
    fixture_count: 60,
    training_backfill_pct: 80,
    training_rows: 400,
    training_target: 500,
    eval_pass_pct: 98,
    eval_corpus_size: 60,
    eval_status: "outcome_full",
    prod_readiness_pct: 88,
    gaps_to_prod: ["MONEY_PATH — tina-gated; bonus tier rules hard-coded"],
    gaps_to_training: ["100 more comp calculations across edge cases"],
    data_sources: [sourceMonday(283), sourceCosRuns(400)],
    wiring_plan: ["Move bonus rules to DB-backed table (P4-BACKEND)"],
    suggested_evals: ["Comp calc accuracy = 100% vs ledger"],
    github_issues: [],
  },
  {
    action_name: "process_fixed_rate_payment",
    class: "paid_deal",
    action_number: 20,
    display_name: "Process Fixed-Rate Payment",
    description: "Money-path: dispatch payment via Mercury / PayPal / Stripe Transfer.",
    handler_file: "creator-actions-fixed-rate-payments-processing.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 90,
    fixtures_pct: 80,
    fixture_count: 35,
    training_backfill_pct: 75,
    training_rows: 263,
    training_target: 350,
    eval_pass_pct: 96,
    eval_corpus_size: 35,
    eval_status: "outcome_partial",
    prod_readiness_pct: 82,
    gaps_to_prod: ["MONEY_PATH — tina-gate stays", "Mercury error-class taxonomy thin"],
    gaps_to_training: ["87 more payment events with reconciliation outcome"],
    data_sources: [
      {
        source: "Mercury / PayPal / Stripe payout APIs",
        description: "Transfer events + failure reasons",
        estimated_rows: 1000,
        cleaning_steps: ["Resolve to creator_id", "Map error codes to taxonomy"],
      },
    ],
    wiring_plan: ["Expand error taxonomy to 12 classes; auto-retry transient"],
    suggested_evals: ["Payment success ≥ 99.5%", "Auto-retry resolves ≥ 80% transient"],
    github_issues: [],
  },
  {
    action_name: "reconcile_payment",
    class: "paid_deal",
    action_number: 21,
    display_name: "Reconcile Payment",
    description: "Money-path: confirm bank settlement matches expected payout.",
    handler_file: "campaign-actions-payment.ts",
    hitl_gate: TINA,
    autonomy_level: "L0",
    handler_pct: 85,
    fixtures_pct: 70,
    fixture_count: 30,
    training_backfill_pct: 60,
    training_rows: 180,
    training_target: 300,
    eval_pass_pct: 94,
    eval_corpus_size: 30,
    eval_status: "outcome_partial",
    prod_readiness_pct: 78,
    gaps_to_prod: ["MONEY_PATH — tina-gate", "FX-conversion edge cases unhandled"],
    gaps_to_training: ["120 more reconciliations"],
    data_sources: [{
      source: "Mercury bank statement export",
      description: "Daily reconciliation feed",
      estimated_rows: 500,
      cleaning_steps: ["Match by reference + amount within $0.01"],
    }],
    wiring_plan: ["Add FX edge-case handler for international creators"],
    suggested_evals: ["Reconciliation match ≥ 99%"],
    github_issues: [],
  },
  {
    action_name: "emit_learning_hook",
    class: "paid_deal",
    action_number: 22,
    display_name: "Emit Learning Hook",
    description: "Append outcome to learning ledger for downstream training.",
    handler_file: "notification-actions.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 100,
    fixtures_pct: 100,
    fixture_count: 40,
    training_backfill_pct: 100,
    training_rows: 40,
    training_target: 40,
    eval_pass_pct: 100,
    eval_corpus_size: 40,
    eval_status: "outcome_full",
    prod_readiness_pct: 95,
    gaps_to_prod: [],
    gaps_to_training: [],
    data_sources: [sourceCosRuns(2000)],
    wiring_plan: ["Maintain"],
    suggested_evals: ["Hook emission rate = 100%"],
    github_issues: [],
  },
  {
    action_name: "emit_graduation_event",
    class: "paid_deal",
    action_number: 23,
    display_name: "Emit Graduation Event",
    description: "Mark creator graduated from organic → paid tier.",
    handler_file: "notification-actions.ts",
    hitl_gate: AUTO,
    autonomy_level: "L0",
    handler_pct: 90,
    fixtures_pct: 70,
    fixture_count: 25,
    training_backfill_pct: 60,
    training_rows: 60,
    training_target: 100,
    eval_pass_pct: 92,
    eval_corpus_size: 25,
    eval_status: "structural_only",
    prod_readiness_pct: 78,
    gaps_to_prod: ["Auto-trigger on $1K GMV not yet wired (P3-REACTIVATION)"],
    gaps_to_training: ["40 more graduations across brands"],
    data_sources: [sourceTikTokEvents(500), sourceCosRuns(60)],
    wiring_plan: ["Wire $1K GMV auto-trigger"],
    suggested_evals: ["Graduation event timeliness < 24h post threshold"],
    github_issues: [],
  },
  {
    action_name: "escalate_to_manager",
    class: "paid_deal",
    action_number: 24,
    display_name: "Escalate to Manager",
    description: "Kill-switch tier: route to AM / VP Ops on SLA breach or anomaly.",
    handler_file: "notification-actions.ts",
    hitl_gate: ALEX,
    autonomy_level: "L0",
    handler_pct: 100,
    fixtures_pct: 100,
    fixture_count: 28,
    training_backfill_pct: 100,
    training_rows: 28,
    training_target: 28,
    eval_pass_pct: 100,
    eval_corpus_size: 28,
    eval_status: "outcome_full",
    prod_readiness_pct: 92,
    gaps_to_prod: ["Alex-decision gate is correct policy — keep"],
    gaps_to_training: ["Expand 5-rule composition coverage to 10 rules"],
    data_sources: [sourceFireflies(200), sourceSlackMiqOps(300)],
    wiring_plan: ["Already shipped (#3615); expand rule set after 1 month of telemetry"],
    suggested_evals: ["Escalation routing accuracy = 100%"],
    github_issues: [3615],
  },
  {
    action_name: "pause_campaign_spend",
    class: "paid_deal",
    action_number: 25,
    display_name: "Pause Campaign Spend",
    description: "Kill-switch: halt all paid spend on a campaign on anomaly trigger.",
    handler_file: "campaign-actions-core.ts",
    hitl_gate: ALEX,
    autonomy_level: "L0",
    handler_pct: 95,
    fixtures_pct: 60,
    fixture_count: 18,
    training_backfill_pct: 50,
    training_rows: 50,
    training_target: 100,
    eval_pass_pct: 95,
    eval_corpus_size: 18,
    eval_status: "structural_only",
    prod_readiness_pct: 82,
    gaps_to_prod: ["Alex-decision gate correct", "Need negative-test fixtures"],
    gaps_to_training: ["50 more pause events with downstream verification"],
    data_sources: [sourceCosRuns(50), sourceSlackMiqOps(100)],
    wiring_plan: ["Add negative test (don't pause when threshold not met)"],
    suggested_evals: ["False-pause rate = 0", "True-pause latency < 10 min"],
    github_issues: [],
  },
  {
    action_name: "auto_revert_rule",
    class: "paid_deal",
    action_number: 26,
    display_name: "Auto-Revert Rule",
    description: "Kill-switch: roll back a deployed automation rule on regression.",
    handler_file: "domains/autonomy/cos/pr-pipeline/auto-pr-runner.ts",
    hitl_gate: ALEX,
    autonomy_level: "L0",
    handler_pct: 90,
    fixtures_pct: 50,
    fixture_count: 15,
    training_backfill_pct: 35,
    training_rows: 35,
    training_target: 100,
    eval_pass_pct: 90,
    eval_corpus_size: 15,
    eval_status: "structural_only",
    prod_readiness_pct: 70,
    gaps_to_prod: [
      "Drift signal (ρ<0.80) from page-hinkley not yet wired to trigger (#3363)",
      "Weekly retrain cron not active (#3364)",
    ],
    gaps_to_training: ["65 more revert events across rule classes"],
    data_sources: [sourceCosRuns(100), sourceSlackMiqOps(50)],
    wiring_plan: [
      "Activate page-hinkley drift monitor (#3363)",
      "Activate weekly retrain cron (#3364)",
      "Wire ρ<0.80 → auto-revert trigger",
    ],
    suggested_evals: ["Auto-revert detects regression within 24h", "False-revert rate < 5%"],
    github_issues: [3363, 3364],
  },
];

export function rollups(actions: AutonomyAction[]) {
  const n = actions.length;
  const avg = (k: keyof AutonomyAction) =>
    actions.reduce((s, a) => s + (a[k] as number), 0) / n;
  return {
    total_actions: n,
    sampling_count: actions.filter((a) => a.class === "sampling").length,
    paid_deal_count: actions.filter((a) => a.class === "paid_deal").length,
    avg_handler_pct: avg("handler_pct"),
    avg_fixtures_pct: avg("fixtures_pct"),
    avg_training_backfill_pct: avg("training_backfill_pct"),
    avg_eval_pass_pct:
      actions.filter((a) => a.eval_pass_pct != null).reduce((s, a) => s + (a.eval_pass_pct ?? 0), 0) /
      actions.filter((a) => a.eval_pass_pct != null).length,
    avg_prod_readiness_pct: avg("prod_readiness_pct"),
    total_training_rows: actions.reduce((s, a) => s + a.training_rows, 0),
    total_training_target: actions.reduce((s, a) => s + a.training_target, 0),
    total_fixtures: actions.reduce((s, a) => s + a.fixture_count, 0),
    actions_at_l0: actions.filter((a) => a.autonomy_level === "L0").length,
    actions_zero_fixtures: actions.filter((a) => a.fixture_count < 20).length,
    actions_outcome_full: actions.filter((a) => a.eval_status === "outcome_full").length,
    actions_no_evals: actions.filter((a) => a.eval_status === "none" || a.eval_status === "structural_only").length,
    money_path_actions: actions.filter((a) => a.action_name.includes("payment") || a.action_name.includes("compensation") || a.action_name.includes("verify_bundle") || a.action_name.includes("count_qualifying") || a.action_name.includes("reconcile")).length,
  };
}
